version: 2

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.PAT}}

updates:
  # Composer
  - package-ecosystem: composer
    directory: /
    versioning-strategy: widen
    schedule: { interval: daily }
    open-pull-requests-limit: 10
    registries: [ github ]
    allow:
      - dependency-type: all # Direct & indirect updates for all packages

  # GitHub Action
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: daily }
    open-pull-requests-limit: 10
